### ISSUE TITLE
Exception with Brute Force in 1.X

### ISSUE THREAD

**Issue by tyrcho** [skjolber/3d-bin-container-packing#514] opened 2022-06-01 17:19 UTC
Hi,

Here is the test case to reproduce the issue: #513 

The packager crashes unexpectedly with `java.lang.IllegalArgumentException: Unexpected count 23, expected 32`

**Comment by skjolber** [comment] 2022-06-07 23:05
I've released a fix, but I am not sure whether I like it or not yet. The problem is that the rotator algorithm is producing numbers in a pattern which make them hard to reuse.

**Comment by skjolber** [comment] 2022-06-07 23:41
Released as [1.2.19](https://github.com/skjolber/3d-bin-container-packing/releases/tag/parent-1.2.19)

**Closed** 2022-06-07 23:40 UTC

**Comment by tyrcho** [comment] 2022-06-10 16:49
thanks ! I'm now using 1.2.19 in production

**Comment by skjolber** [comment] 2022-06-11 01:15
@tyrcho so the main thing preventing you from switching to 2.x is the performance?
