### ISSUE TITLE
use  FastBruteForcePackager get wrong result

### ISSUE THREAD

**Issue by ZhaoFan777** [skjolber/3d-bin-container-packing#769] opened 2023-10-10 08:08 UTC
### data:
products.add(new StackableItem(Box.newBuilder().withId("goods1")
                .withSize(295, 190, 160).withRotate3D().withWeight(0).build(), 5));
        products.add(new StackableItem(Box.newBuilder().withId("goods2")
                .withSize(245, 190, 160).withRotate3D().withWeight(0).build(), 9));
        Container container = Container.newBuilder()
                .withDescription("box")
                .withSize(500, 500, 500)
                .withEmptyWeight(0)
                .withMaxLoadWeight(1)
                .build();
packager:### 
FastBruteForcePackager packager = FastBruteForcePackager.newBuilder().build();
PackagerResult result = packager
                .newResultBuilder()
                .withContainers(containerItems)
                .withStackables(products)
                .build();

result:
there is an overlap.
![image](https://github.com/skjolber/3d-bin-container-packing/assets/86393895/d4484f40-b1d9-4d14-a3da-9ae883999f00)

**Comment by skjolber** [comment] 2023-10-12 20:17
@ZhaoFan777 I am not able to reproduce this in master.

Are you using the latest version of the library? An issues similar to this was fixed in the latest release.

Also, what kind of visualizer is that? :D

**Comment by skjolber** [comment] 2023-10-12 20:21
See `issue769` branch

**Comment by ZhaoFan777** [comment] 2023-10-19 06:26
> @ZhaoFan777我无法在 master 中重现这一点。
> 
> 您使用的是最新版本的库吗？与此类似的问题已在最新版本中修复。
>         <dependency>
            <groupId>com.github.skjolber.3d-bin-container-packing</groupId>
            <artifactId>core</artifactId>
            <version>3.0.8</version>
        </dependency> 
> 另外，那是什么样的可视化工具？💯  
dash

**Comment by skjolber** [comment] 2023-10-19 21:05
@ZhaoFan777 do you still get this in version [3.0.9](https://github.com/skjolber/3d-bin-container-packing/releases/tag/parent-3.0.9)?

**Closed** 2023-10-26 21:27 UTC
Labels: work in progress
